name: elders_word_dungeon_android
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flame: ^1.13.1
  audioplayers: ^5.0.0
  google_fonts: ^6.1.0
  shared_preferences: ^2.3.1
  flutter_dotenv: ^5.2.1
  google_mobile_ads: ^2.3.0
  connectivity_plus: ^5.0.2
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/data/level_1.json
    - assets/data/level_2.json
    - assets/data/level_3.json
    - assets/data/level_4.json
    - assets/data/level_5.json
    - assets/data/level_6.json
    - assets/data/level_7.json
    - assets/data/level_8.json
    - assets/data/level_9.json